### ISSUE TITLE
close div in resume.hbs

### ISSUE THREAD

**Issue by DavidEngland** [jsonresume/jsonresume-theme-boilerplate#15]
Should there not be a </div> after the last partial to close the <div id="resume">?

**Comment by ishu3101** [comment]
Yeah, there should be one. I forgot to close the div after I refactored the code to make use of Handelbar partials.

**Comment by ciderpunx** [comment]
OK?

**Comment by XuluWarrior** [comment]
This issue is marked as closed but the pull request was never merged into this repository.  Can we reopen it?
