### ISSUE TITLE
Use .hbs file-ending

### ISSUE THREAD

**Issue by adius** [jsonresume/jsonresume-theme-boilerplate#9]
You should use the standard `.hbs` file-ending for handlebars templates.
Then editors can automatically use the right syntax highlighting and people know what to expect!

**Comment by erming** [comment]
Yeah, that's a good idea. Fixed it: https://github.com/jsonresume/jsonresume-theme-boilerplate/commit/1b5b51e21f3bfa2dff0d971bf7de4ec433816e2a
